import os
from google import genai
from google.genai import types
from agents.planner import PlannerAgent
from dotenv import load_dotenv
from utils.ai_client import gemini as client 

load_dotenv()


class DeveloperAgent:
    """
    Generates frontend code based on steps generated by PlannerAgent.
    Creates a single HTML file with inline CSS and JavaScript.
    """

    def __init__(self, model_name="gemini-2.5-flash"):
        self.client = client
        self.model_name = model_name
        self.planner = PlannerAgent()

    def _generate_code(self, prompt: str) -> str:
        """Call Gemini API to generate code."""
        config = types.GenerateContentConfig(temperature=0.2, max_output_tokens=100000)
        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt,
            config=config
        )

        code = getattr(response, "text", None)
        if not code and hasattr(response, "candidates"):
            parts = response.candidates[0].content.parts
            code = "".join(p.text for p in parts if hasattr(p, "text"))

        if code:
            code = code.strip()
            if code.startswith("```html"):
                code = code[7:]
            elif code.startswith("```"):
                code = code[3:]
            if code.endswith("```"):
                code = code[:-3]
            return code.strip()
        return None

    def generate_project(self, project_name: str, steps: str, user_message: str):
        """Generate a single HTML file based on PlannerAgent steps."""
        # 1️⃣ Generate steps
        print(f"Generated steps:\n{steps}\n")

        # 2️⃣ Prepare prompt for code generation
        prompt = f"""
        You are the Developer Agent of CODEXA.

        Your task is to generate a complete working HTML file
        (with inline CSS and JavaScript) based on the user's idea.

        USER IDEA:
        {user_message}

        PROJECT PLAN (from Planner Agent):
        """
        for i, step in enumerate(steps, 1):
            prompt += f"- {step}\n"

        prompt += """
        Build the actual full implementation of the user's idea.
        Do NOT create anything related to steps, checklists, simulations, or placeholders.

        Requirements:
        - Use inline CSS for styling.
        - Use JavaScript for functional behavior.
        - Build a clean, modern, realistic UI based on the user's idea.
        - Fully implement core functionality.
        - Do NOT include explanations or comments.
        - Return ONLY a complete <html>...</html> file.
        """



        code = self._generate_code(prompt)
        if not code:
            print("❌ Code generation failed.")
            return None, None  # Consistent return type

        # 4️⃣ Save file
        os.makedirs("output", exist_ok=True)
        file_path = os.path.join("output", f"{project_name.replace(' ','_')}.html")
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
            print(f"✅ HTML project generated: {file_path}")
            # Storing code in database PENDING
            return{ "file_path":file_path,"code":code}
        except Exception as e:
            print(f"❌ Failed to save file: {e}")
            return None, None
